// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {nameTokenizer} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: ")rOQOQOOOOOO'#Cx'#CxOVOQO'#CaO_OQO'#C`OQOQO'#C_QdOQOOOOOO-E6v-E6vOOOO,58z,58zOlOQO'#CdOtOQO'#CcOyOSO,58yO!OOQO'#CnO!ZOQO'#CpO!`OQO'#CoOOOO'#Cw'#CwOOOO'#DP'#DPOOOO'#Cz'#CzQdOQOOO!eOQO,58}OOOO'#Cy'#CyO!jOSO'#CkOOOO1G.e1G.eO!rOQO,59[O!zOQO,59ZOOOO-E6x-E6xO#YOQO1G.iOOOO-E6w-E6wOOOO,59V,59VO#_OQO1G.vO#dOQO1G.sO#iOQO'#CvOQOQO'#CuOOOO'#C|'#C|O#nOQO1G.uO#|OQO7+$TO$UOQO7+$bO$aOQO7+$_OOOO,59b,59bO$iOQO'#CpO$nOQO,59aOOOO-E6z-E6zO$sOQO'#ChOOOO<<Go<<GoO$xOQO<<GoO$}OQO'#CqOOOO<<G|<<G|O%VOQO<<G|O%_OQO<<G|OOOO'#C{'#C{O%jOQO<<GyOOOO<<Gy<<GyO%rOQO,59[OOOO1G.{1G.{O%wOQO,59SOOOOAN=ZAN=ZO%|OQO,59]O&ROQO,59_O%QOQO'#CsOOOOAN=hAN=hO&WOQOAN=hOOOO-E6y-E6yOOOOAN=eAN=eOOOO1G.n1G.nOOOO1G.w1G.wO&`OQO1G.yOOOOG23SG23SOOOO7+$e7+$e",
  stateData: "&s~OrPO~OrPOUTX~OUVO~OU^OrPO~OrPOXWX~OXbO~O`cO~OrPOXbXUbX~OXfO~OUgO~OYiO~OUkO`cO~OYlOrPO~OXnOUcaqcarca~OZrO~OZsO~OUtO~OvuO~OXnOUciqcirci~OUzO]yO~O]yOt|OUdq~OU!SOrPO~OX!TO~OU!UO~OY!VO~OU!WO~Of!XOh!YO~Ot!ZOUdy~O]yOt!ZOUdy~OU!_OrPO~OYlO~O^!`O~Ou!aO~OY!bO~Ot!ZOUd!R~Ou!dO~OvXth]UYf^Zu`r~",
  goto: "$ktPPPux{P!O!RPPP!UPP!_P!b!f!r!z#TP#WP#b#f!b#j#}$T$Z$aPP$gRTORSORRORYSRXSQ{rQ!OsR!]!PReYT_TaS[TaQmfVvot!RS_TaT!Qt!RW]Tat!RRwoR!PsQ}sS![!O!PR!c!]TpgqTogqQQOUUQWZQWS]ZTafot!RQdYRjdQaTRhaQ!RtR!^!RQqgRxqT`Ta",
  nodeNames: "⚠ GenName Document Header FactionLine FactionName LineEnd ArmyInfoLine ArmyName Delineator Number PointsMarker CommandClause Comma CommandMarker DelineatorLine DelineatorChar TacticalGroup Name UnitComplex Unit TacomDesignator TacomMarker Multiplier MultiplierMarker MountedUnitLine MountedPrefix BlankLine",
  maxTerm: 38,
  skippedNodes: [0,1],
  repeatNodeCount: 5,
  tokenData: ",U~RwOY#lYZ#qZ]#l]^#v^p#lpq$Oqx#lxy%Uyz%]z|#l|}%d}!O%k!O!Q#l!Q![%u![!_#l!_!`%k!`!e#l!e!f&X!f!r#l!r!s'z!s!v#l!v!w(t!w!z#l!z!{)e!{!}#l!}#O)l#O#R#l#R#S%k#S#V#l#V#W+O#W#d#l#d#e+Z#e#l#l#l#m)e#m$Ih#l$Ih$Ii%k$Ii;'S#l;'S;=`,O<%lO#l~#qOr~~#vOU~~#{PU~YZ#q~$TTr~pq$d}!O$v!_!`$v#R#S$v$Ih$Ii$vP$gTpq$d}!O$v!_!`$v#R#S$v$Ih$Ii$vP$yPpq$|P%RPXPpq$|~%]Ot~r~~%dOu~r~~%kO]~r~~%rP`Qr~pq$|~%|PY~r~!Q![&P~&UPY~!Q![&P~&^Rr~!o!p&g!q!r&r#c#d'[~&jP!f!g&m~&rO^~~&uP!o!p&x~&{P!o!p'O~'RP!c!d'U~'XP!p!q&g~'_P#a#b'b~'eP#a#b'h~'kP#T#U'n~'qP#b#c't~'wP#W#X&m~(PQr~!q!r(V!v!w(i~(YP!k!l(]~(`P!p!q(c~(fP!v!w(i~(lP!u!v(o~(tOZ~~(yPr~!c!d(|~)PP!e!f)S~)VP!q!r)Y~)]P!o!p)`~)eOf~~)lOh~r~~)q`r~!Q!R*s!R!S*s!S!T*s!T!U*s!U!V*s!V!W*s!W!X*s!X!Y*s!Y!Z*s!Z![*s!f!g*s!g!h*s!v!w*s#W#X*s#X#Y*s#h#i*s~*vP#P#Q*y~+OOv~~+TQr~#a#b't#c#d'[~+`Qr~#c#d+f#h#i+x~+iP#]#^+l~+oP#b#c+r~+uP#h#i+x~+{P#g#h(o~,RP;=`<%l#l",
  tokenizers: [nameTokenizer, 0, 1],
  topRules: {"Document":[0,2]},
  tokenPrec: 251
})
